
server:
    error:
        include-message: always
        include-stacktrace: never
spring:
    profiles:
        active: prod
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DATABASE_PASSWORD}
        platform: postgres
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USER}
    jackson:
        deserialization:
            use_java_array_for_json_array: true
        serialization:
            write-dates-as-timestamps: false
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                    create_namespaces: true
                show_sql: false
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    web:
        resources:
            static-locations: classpath:/static/browser
    security:
        rememberme.key: ${REMEMBER_ME_KEY}
        basic:
            enabled: true
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
            resource:
                user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
    mail:
        host: ${SMTP_HOST}
        port: ${SMTP_PORT:587}
        protocol: ${SMTP_PROTOCOL}
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${SMTP_AUTH}
                    ssl.trust: "${SMTP_SSL_TRUST:sztyro.com}"
                    starttls:
                        enable: true
app:
    version: @project.version@
    mail.info.recipient: ${INFO_RECIPIENT}